#ifndef DEFAULTS_H
#define DEFAULTS_H

#define DEF_TOOLBAR_HEIGHT   50
#define DEF_STATUSBAR_HEIGHT 30
#define DEF_ITEMLIST_WIDTH   200
#define DEF_GRID_BTN_SIZE    50
#define DEF_GRID_THICKNESS   2
#define DEF_CANVAS_COLUMN    8
#define DEF_CANVAS_ROW       8

#endif
